### 获取所有 books
GET http://localhost:8080/books
Content-Type: application/json

### 创建新的 book
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Thinking in Java"
}

### 获取特定 book
GET http://localhost:8080/books/{replace_with_item_id}
Content-Type: application/json

### 更新特定 item
PUT http://localhost:8080/books/{replace_with_item_id}
Content-Type: application/json

{
  "name": "Updated Item"
}

### 删除特定 item
DELETE http://localhost:8080/books/{replace_with_item_id}

### 程序退出
GET http://localhost:8080/exit
Content-Type: application/json
